DROP USER `_USERNAME_`@_HOST_;
CREATE USER `_USERNAME_`@_HOST_ IDENTIFIED BY '_PASSWORD_';

DROP DATABASE IF EXISTS `_DBNAME_`;
CREATE DATABASE `_DBNAME_` DEFAULT CHARACTER SET `utf8` DEFAULT COLLATE `utf8_general_ci`;

GRANT ALL PRIVILEGES ON `_DBNAME_`.* TO `_USERNAME_`@_HOST_;
FLUSH PRIVILEGES;
